--
-- Dumping data for table `controllTxtItems`
--

INSERT INTO `controllTxtItems` VALUES ('portal','accountSettings','main','bottom','Controll-Default: This is portal-accountSettings-main-bottom<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','accountSettings','main','identities','Controll-Default: This is portal-accountSettings-main-identities<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','accountSettings','main','managed','Controll-Default: This is portal-accountSettings-main-managed<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','accountSettings','main','top','Controll-Default: This is portal-accountSettings-main-top<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','addUpgrade','main','bottom','Controll-Default: This is portal-addUpgrade-main-bottom<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','addUpgrade','main','step1','Controll-Default: This is portal-addUpgrade-main-step1<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','addUpgrade','main','step2','Controll-Default: This is portal-addUpgrade-main-step2<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','addUpgrade','main','step3','Controll-Default: This is portal-addUpgrade-main-step3<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','addUpgrade','main','step4','Controll-Default: This is portal-addUpgrade-main-step4<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','addUpgrade','main','top','Controll-Default: This is portal-addUpgrade-main-top<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','index','main','bottom','Controll-Default: This is portal-index-main-bottom<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','index','main','multiple','Controll-Default: This is portal-index-main-multiple<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','index','main','top','Controll-Default: This is portal-index-main-top<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','membershipHistory','main','bottom','Controll-Default: This is portal-membershipHistory-main-bottom<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','membershipHistory','main','top','Controll-Default: This is portal-membershipHistory-main-top<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','portal','main','bottom','Controll-Default: This is portal-portal-main-bottom<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','portal','main','people','Controll-Default: This is portal-portal-main-people<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','portal','main','plan','Controll-Default: This is portal-portal-main-plan<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','portal','main','purchased','Controll-Default: This is portal-portal-main-purchased<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.'),
	('portal','portal','main','top','Controll-Default: This is portal-portal-main-top<br/>Custom HTML that can replaced with a custom value in the Controll Admin App under Edit Custom Text.<br/> Default text can be suppressed in the configuration file.');
